//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayNGoEmpDetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empID { get; set; }
        public string empFName { get; set; }
        public string empLName { get; set; }
        public string empContact { get; set; }
        public string empAddress { get; set; }
    }
}
